### ISSUE TITLE
Android Tutorial - Step 6

### ISSUE THREAD

**Issue by Bumler** [firebase/friendlychat#102]
My application keeps crashing after finishing the steps in step 6. I believe I have followed the instructions exactly and continue to get the error
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.google.firebase.codelab.friendlychat, PID: 9522
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.firebase.codelab.friendlychat/com.google.firebase.codelab.friendlychat.MainActivity}: java.lang.IllegalArgumentException: Given String is empty or null
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
                      at android.app.ActivityThread.access$900(ActivityThread.java:157)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5527)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
                   Caused by: java.lang.IllegalArgumentException: Given String is empty or null
                      at com.google.android.gms.common.internal.zzab.zzhr(Unknown Source)
                      at com.google.android.gms.internal.zzafi$zza$zza.<init>(Unknown Source)
                      at com.google.firebase.auth.FirebaseAuth.zza(Unknown Source)
                      at com.google.firebase.auth.FirebaseAuth.<init>(Unknown Source)
                      at com.google.android.gms.internal.zzaft.<init>(Unknown Source)
                      at com.google.firebase.auth.FirebaseAuth.zzc(Unknown Source)
                      at com.google.firebase.auth.FirebaseAuth.zzb(Unknown Source)
                      at com.google.firebase.auth.FirebaseAuth.getInstance(Unknown Source)
                      at com.google.firebase.codelab.friendlychat.MainActivity.onCreate(MainActivity.java:112)
                      at android.app.Activity.performCreate(Activity.java:6272)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494) 
                      at android.app.ActivityThread.access$900(ActivityThread.java:157) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:5527) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) 

The app does not crash if I comment out the following section:
        // Initialize Firebase Auth
        mFirebaseAuth = FirebaseAuth.getInstance();
        mFirebaseUser = mFirebaseAuth.getCurrentUser();
        if (mFirebaseUser == null) {
            // Not signed in, launch the Sign In activity
            startActivity(new Intent(this, SignInActivity.class));
            finish();
            return;
        } else {
            mUsername = mFirebaseUser.getDisplayName();
            if (mFirebaseUser.getPhotoUrl() != null) {
                mPhotoUrl = mFirebaseUser.getPhotoUrl().toString();
            }
        }

I've tried moving the FireBase Auth initialization to various places in the onCreate method to no avail. I will be trying to recreate this on another machine in the next couple days. 

Any help is greatly appreciated.

**Comment by Divala** [comment]
I think you should update your Google play services in SDK Manager and also
update firebase auth to 9.4.0 (latest version )

**Comment by Bumler** [comment]
Thanks! I made sure my play services were up to date and redownloaded my google config files and it seems to be working now.
