### ISSUE TITLE
Can't sign in on my SAMSUNG_SM_G930A (Android 6.0.1, API 23)

### ISSUE THREAD

**Issue by jkozh** [firebase/friendlychat#133]
On my actual Samsung device SAMSUNG_SM_G930A (Android 6.0.1, API 23), I use android-start code.
When I click on Sign In (via Google) button, I choose my account then click on sign in. And I see the message an Authentication failed on my screen and this warning in logs : 
```
D/SignInActivity: signInWithCredential:onComplete:false
W/SignInActivity: signInWithCredential
                  com.google.firebase.FirebaseException: An internal error has occurred. [ Internal error. ]
                      at com.google.android.gms.internal.zzbix.zzcb(Unknown Source)
                      at com.google.android.gms.internal.zzbiu$zzj.zza(Unknown Source)
                      at com.google.android.gms.internal.zzbjf.zzcc(Unknown Source)
                      at com.google.android.gms.internal.zzbjf$zza.onFailure(Unknown Source)
                      at com.google.android.gms.internal.zzbja$zza.onTransact(Unknown Source)
                      at android.os.Binder.execTransact(Binder.java:453)
```

It can't sign in only on my Samsung device, because I tried other common devices and emulators, and it works fine on them.

**Comment by Divala** [comment]
Enable Google as an authentication method in firebase console

**Comment by jkozh** [comment]
@Divala ,  My Google as an authentication method in firebase console was already enabled. I tried other common devices and emulators, and it works fine on them, but not on my Samsung.

**Comment by kroikie** [comment]
I wonder if it could be the version of Google Play Services on the device? Could you update it and try again if this is still an issue.
